apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mkjcyr2j4-python 
  janus-idp.io/tekton: mkjcyr2j4-python
  backstage.io/kubernetes-id: mkjcyr2j4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mkjcyr2j4-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml